//
//  PlayInteractor.swift
//  PitchPerfect
//
//  Created by prongbang on 8/4/2562 BE.
//  Copyright (c) 2562 prongbang. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PlayBusinessLogic
{
    func doSomething(request: Play.Something.Request)
}

protocol PlayDataStore
{
    var url: URL? { get set }
}

class PlayInteractor: PlayBusinessLogic, PlayDataStore
{
    var url: URL?
    
    var presenter: PlayPresentationLogic?
    var worker: PlayWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func doSomething(request: Play.Something.Request)
    {
        print("url: \(String(describing: url))")
        
        worker = PlayWorker()
        worker?.doSomeWork()
        
        let response = Play.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
