//
//  RecordRouter.swift
//  PitchPerfect
//
//  Created by prongbang on 8/4/2562 BE.
//  Copyright (c) 2562 prongbang. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol RecordRoutingLogic
{
    func routeToPlay(segue: UIStoryboardSegue?)
}

protocol RecordDataPassing
{
    var dataStore: RecordDataStore? { get }
}

class RecordRouter: NSObject, RecordRoutingLogic, RecordDataPassing
{
    weak var viewController: RecordViewController?
    var dataStore: RecordDataStore?
    
    // MARK: Routing
    
    func routeToPlay(segue: UIStoryboardSegue?)
    {
        if let segue = segue {
            let destinationVC = segue.destination as! PlayViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToSomewhere(source: dataStore!, destination: &destinationDS)
            navigateToSomewhere(source: viewController!, destination: destinationVC)
        } else {
            let storyboard = UIStoryboard(name: "Main", bundle: nil)
            let destinationVC = storyboard.instantiateViewController(withIdentifier: "PlayViewController") as! PlayViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToSomewhere(source: dataStore!, destination: &destinationDS)
            navigateToSomewhere(source: viewController!, destination: destinationVC)
        }
    }
    
    // MARK: Navigation
    
    func navigateToSomewhere(source: RecordViewController, destination: PlayViewController)
    {
        source.show(destination, sender: nil)
    }
    
    // MARK: Passing data
    
    func passDataToSomewhere(source: RecordDataStore, destination: inout PlayDataStore)
    {
        destination.url = source.url
    }
}
