//
//  RecordPresenter.swift
//  PitchPerfect
//
//  Created by prongbang on 8/4/2562 BE.
//  Copyright (c) 2562 prongbang. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RecordPresentationLogic
{
  func presentSomething(response: Record.Something.Response)
}

class RecordPresenter: RecordPresentationLogic
{
  weak var viewController: RecordDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Record.Something.Response)
  {
    let viewModel = Record.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
